language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - nvm install 12
  - nvm alias default 12
  - nvm use 12
  - npm install @angular/cli -g

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  - provider: pages
    script:
      - ng build --prod --base-href https://pooriapoorsarvi.github.io/Personal-Site-Front-End/
      - cp dist/Personal-Site-Front-End/index.html dist/Personal-Site-Front-End/404.html
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/Personal-Site-Front-End
    on:
- provider: s3
    script:
      - ng build --prod
    access_key_id: $ACCESS_KEY_ID_AWS
    secret_access_key: $SECRET_ACCESS_KEY_AWS
    bucket: "ppt.portfolio"
    skip_cleanup: true
    acl: public_read
    local_dir: ./dist/Personal-Site-Front-End/
    region: us-east-2
