language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - nvm install 12
  - nvm alias default 12
  - nvm use 12
  - npm install @angular/cli -g

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod --base-href "https://pooriapoorsarvi.github.io/Personal-Site-Front-End/"


deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./dist/
    on:

