language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - nvm install 12
  - nvm alias default 12
  - nvm use 12
  - npm install @angular/cli -g

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod


deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  bucket: "ppt.portfolio"
  skip_cleanup: true
  local_dir: ./dist/Personal-Site-Front-End/
