language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - apt install zip unzip
  - nvm install 12
  - nvm alias default 12
  - nvm use 12
  - npm install @angular/cli -g

cache:
  yarn: true
  directories:
    - node_modules

script :
  - npm run build:ssr
  - mv ./dist ./ebs-package/dist
  - zip -r ./output_file.zip ./ebs-package/dist ./ebs-package/package.json

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  region: "us-east-2"
  app: "PersonalPortfolioFrontEnd"
  env : "Personalportfoliofrontend-env"
  zip_file: "./output_file.zip"
  #  The clean up is skipped so that the jar file would not be removed
  skip_cleanup: true
