language: node_js
node_js:
 - "12"
sudo : true
branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - nvm alias default 12
  - nvm use 12
  - npm install @angular/cli -g

cache:
  yarn: true
  directories:
    - node_modules

script :
  - npm run build:ssr
  - rm ./package.json
  - mv ./ebs-package/package.json ./package.json
  - zip -r ./output_file.zip ./dist ./package.json

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID_AWS
  secret_access_key: $SECRET_ACCESS_KEY_AWS
  region: "us-east-2"
  app: "PersonalPortfolioFrontEnd"
  env : "Personalportfoliofrontend-env"
  zip_file: "./output_file.zip"
  bucket_name : "ebs-personal-portfolio-front"
  #  The clean up is skipped so that the jar file would not be removed
  skip_cleanup: true
